pref('extensions.stylishmod.autoimportant.enabled', false);
pref('extensions.stylishmod.autoimportant.key', '33');
pref('extensions.stylishmod.autoimportant.text', '!important;');
pref('extensions.stylishmod.custom-insert-popup', '600px');
pref('extensions.stylishmod.insert-text', '-moz-appearance: none !important;<>display: none !important;<>background: url("") !important;<>background: url("") no-repeat !important;<>list-style-image: url("") !impotant;<>-moz-image-region: rect(0px 0px 0px 0px) !important;');
pref('extensions.stylishmod.darktheme', '0');
pref('extensions.stylishmod.editoralert', false);
pref('extensions.stylishmod.errorstop', '0');
pref('extensions.stylishmod.externalEditor', 'C:\Windows\System32\write.exe');
pref('extensions.stylishmod.findtext', '');
pref('extensions.stylishmod.icon-text', '3');
pref('extensions.stylishmod.id', 0);
pref('extensions.stylishmod.rainbowpicker', false);
pref('extensions.stylishmod.reachedtoptext', 'Reached end, continued from top');
pref('extensions.stylishmod.reachedbottomtext', 'Reached top, continued from bottom');
pref('extensions.stylishmod.removefocus', true);
pref('extensions.stylishmod.scalegray', 'yes');
pref('extensions.stylishmod.scratchpad1Text', '');
pref('extensions.stylishmod.scratchpad2Text', '');
pref("extensions.stylishmod.symbol1", '2606,2606');
pref("extensions.stylishmod.symbol2", '25BA,23B8');
pref("extensions.stylishmod.symbol3", '23B9,25C4');
pref('extensions.stylishmod.tag-sep', '2606');
pref('extensions.stylishmod.windowalert', false);

pref('extensions.stylishmod.toolbar2', false);
pref('extensions.stylishmod.toolbar3', false);
pref('extensions.stylishmod.toolbar4', false);
pref('extensions.stylishmod.toolbar5', false);
pref('extensions.stylishmod.toolbar6', false);
pref('extensions.stylishmod.toolbar7', false);

pref('extensions.stylishmod.add-tag', true);
pref('extensions.stylishmod.auto-important', true);
pref('extensions.stylishmod.blank-style', true);
pref('extensions.stylishmod.bytes', true);
pref('extensions.stylishmod.clear1', false);
pref('extensions.stylishmod.clear2', false);
pref('extensions.stylishmod.clone-style', true);
pref('extensions.stylishmod.color-format', true);
pref('extensions.stylishmod.comment-group', true);
pref('extensions.stylishmod.comment-text', true);
pref('extensions.stylishmod.convert-class', true);
pref('extensions.stylishmod.convert-id', true);
pref('extensions.stylishmod.copy', true);
pref('extensions.stylishmod.curly-bracket', true);
pref('extensions.stylishmod.cursor', true);
pref('extensions.stylishmod.custom-insert', true);
pref('extensions.stylishmod.cut', true);
pref('extensions.stylishmod.export-style', true);
pref('extensions.stylishmod.external-editor', true);
pref('extensions.stylishmod.findbar', true);
pref('extensions.stylishmod.flex1', false);
pref('extensions.stylishmod.flex2', false);
pref('extensions.stylishmod.flex3', false);
pref('extensions.stylishmod.flex4', false);
pref('extensions.stylishmod.flex5', false);
pref('extensions.stylishmod.go-to-end', true);
pref('extensions.stylishmod.go-to-top', true);
pref('extensions.stylishmod.insert', true);
pref('extensions.stylishmod.line', true);
pref('extensions.stylishmod.make-important', true);
pref('extensions.stylishmod.paste', true);
pref('extensions.stylishmod.pick-color', true);
pref('extensions.stylishmod.position', true);
pref('extensions.stylishmod.preview', true);
pref('extensions.stylishmod.redo', true);
pref('extensions.stylishmod.removeXUL', true);
pref('extensions.stylishmod.restore-down', false);
pref('extensions.stylishmod.restore-window', false);
pref('extensions.stylishmod.save-button-alt', true);
pref('extensions.stylishmod.save-button-disabled', true);
pref('extensions.stylishmod.save-button-enabled', true);
pref('extensions.stylishmod.scratchpad1', true);
pref('extensions.stylishmod.scratchpad2', true);
pref('extensions.stylishmod.select', true);
pref('extensions.stylishmod.settings', true);
pref('extensions.stylishmod.space1', false);
pref('extensions.stylishmod.space2', false);
pref('extensions.stylishmod.spacer1', false);
pref('extensions.stylishmod.spacer2', false);
pref('extensions.stylishmod.spacer3', false);
pref('extensions.stylishmod.spacer4', false);
pref('extensions.stylishmod.spacer5', false);
pref('extensions.stylishmod.sq-bracket', true);
pref('extensions.stylishmod.styleid', true);
pref('extensions.stylishmod.style-name', true);
pref('extensions.stylishmod.style-page', true);
pref('extensions.stylishmod.togglebars', true);
pref('extensions.stylishmod.undo', true);
pref('extensions.stylishmod.undo-all', true);
pref('extensions.stylishmod.unobfuscate', true);
pref('extensions.stylishmod.unpreview', false);
pref('extensions.stylishmod.update', true);
pref('extensions.stylishmod.wrap-lines', true);

pref('extensions.stylishmod.label.add-tag', 'Add Tag');
pref('extensions.stylishmod.label.auto-important', 'Auto Important');
pref('extensions.stylishmod.label.blank-style', 'Blank Style');
pref('extensions.stylishmod.label.bytes', 'Bytes');
pref('extensions.stylishmod.label.clear1', 'Clear1');
pref('extensions.stylishmod.label.clear2', 'Clear2');
pref('extensions.stylishmod.label.clone-style', 'Clone Style');
pref('extensions.stylishmod.label.color-format', 'Color Format');
pref('extensions.stylishmod.label.comment-group', 'Comment Group');
pref('extensions.stylishmod.label.comment-text', 'Comment Text');
pref('extensions.stylishmod.label.convert-class', 'Convert Class');
pref('extensions.stylishmod.label.convert-id', 'Convert ID');
pref('extensions.stylishmod.label.copy', 'Copy');
pref('extensions.stylishmod.label.curly-bracket', 'Curly Bracket');
pref('extensions.stylishmod.label.cursor', 'Cursor At');
pref('extensions.stylishmod.label.custom-insert', 'Insert Text');
pref('extensions.stylishmod.label.cut', 'Cut');
pref('extensions.stylishmod.label.export-style', 'Export Style');
pref('extensions.stylishmod.label.external-editor', 'External Editor');
pref('extensions.stylishmod.label.findbar', 'Findbar');
pref('extensions.stylishmod.label.flex1', 'Flex Space');
pref('extensions.stylishmod.label.flex2', 'Flex Space');
pref('extensions.stylishmod.label.flex3', 'Flex Space');
pref('extensions.stylishmod.label.flex4', 'Flex Space');
pref('extensions.stylishmod.label.flex5', 'Flex Space');
pref('extensions.stylishmod.label.go-to-end', 'Go To End');
pref('extensions.stylishmod.label.go-to-top', 'Go To Top');
pref('extensions.stylishmod.label.insert', 'Insert');
pref('extensions.stylishmod.label.line', 'Go To Line #');
pref('extensions.stylishmod.label.make-important', 'Make Important');
pref('extensions.stylishmod.label.paste', 'Paste');
pref('extensions.stylishmod.label.pick-color', 'Insert Color');
pref('extensions.stylishmod.label.position', 'Position');
pref('extensions.stylishmod.label.preview', 'Preview');
pref('extensions.stylishmod.label.redo', 'Redo');
pref('extensions.stylishmod.label.removeXUL', 'Remove XUL');
pref('extensions.stylishmod.label.restore-down', 'Restore Down');
pref('extensions.stylishmod.label.restore-window', 'Restore Window');
pref('extensions.stylishmod.label.save-button-alt', 'Save');
pref('extensions.stylishmod.label.save-button-disabled', 'Save/Disabled');
pref('extensions.stylishmod.label.save-button-enabled', 'Save/Enabled');
pref('extensions.stylishmod.label.scratchpad1', 'Scratchpad1');
pref('extensions.stylishmod.label.scratchpad2', 'Scratchpad2');
pref('extensions.stylishmod.label.select', 'Select All');
pref('extensions.stylishmod.label.settings', 'Settings');
pref('extensions.stylishmod.label.space1', 'Space');
pref('extensions.stylishmod.label.space2', 'Space');
pref('extensions.stylishmod.label.spacer1', 'Spacer');
pref('extensions.stylishmod.label.spacer2', 'Spacer');
pref('extensions.stylishmod.label.spacer3', 'Spacer');
pref('extensions.stylishmod.label.spacer4', 'Spacer');
pref('extensions.stylishmod.label.spacer5', 'Spacer');
pref('extensions.stylishmod.label.sq-bracket', 'Sq Bracket');
pref('extensions.stylishmod.label.styleid', 'ID');
pref('extensions.stylishmod.label.style-name', 'Name');
pref('extensions.stylishmod.label.style-page', 'Style Page');
pref('extensions.stylishmod.label.togglebars', 'Toggler');
pref('extensions.stylishmod.label.undo', 'Undo');
pref('extensions.stylishmod.label.undo-all', 'Undo All');
pref('extensions.stylishmod.label.unobfuscate', 'Unobfuscate');
pref('extensions.stylishmod.label.unpreview', 'Un-Preview');
pref('extensions.stylishmod.label.update', 'Update Url');
pref('extensions.stylishmod.label.wrap-lines', 'Wrap lines');

pref('extensions.stylishmod.move.add-tag', '4,88');
pref('extensions.stylishmod.move.auto-important', '3,12');
pref('extensions.stylishmod.move.blank-style', '2,44');
pref('extensions.stylishmod.move.bytes', '1,40');
pref('extensions.stylishmod.move.clear1', '4,4');
pref('extensions.stylishmod.move.clear2', '4,12');
pref('extensions.stylishmod.move.clone-style', '5,46');
pref('extensions.stylishmod.move.color-format', '2,16');
pref('extensions.stylishmod.move.comment-group', '2,9');
pref('extensions.stylishmod.move.comment-text', '2,8');
pref('extensions.stylishmod.move.convert-class', '4,3');
pref('extensions.stylishmod.move.convert-id', '4,4');
pref('extensions.stylishmod.move.copy', '2,40');
pref('extensions.stylishmod.move.curly-bracket', '2,41');
pref('extensions.stylishmod.move.cursor', '3,20');
pref('extensions.stylishmod.move.custom-insert', '2,6');
pref('extensions.stylishmod.move.cut', '2,42');
pref('extensions.stylishmod.move.export-style', '1,24');
pref('extensions.stylishmod.move.external-editor', '6,24');
pref('extensions.stylishmod.move.findbar', '3,32');
pref('extensions.stylishmod.move.flex1', '1,56');
pref('extensions.stylishmod.move.flex2', '2,48');
pref('extensions.stylishmod.move.flex3', '3,28');
pref('extensions.stylishmod.move.flex4', '3,29');
pref('extensions.stylishmod.move.flex5', '3,30');
pref('extensions.stylishmod.move.go-to-end', '5,50');
pref('extensions.stylishmod.move.go-to-top', '5,51');
pref('extensions.stylishmod.move.insert', '2,4');
pref('extensions.stylishmod.move.line', '3,16');
pref('extensions.stylishmod.move.make-important', '6,80');
pref('extensions.stylishmod.move.paste', '2,42');
pref('extensions.stylishmod.move.pick-color', '2,12');
pref('extensions.stylishmod.move.position', '1,8');
pref('extensions.stylishmod.move.preview', '3,4');
pref('extensions.stylishmod.move.redo', '2,24');
pref('extensions.stylishmod.move.removeXUL', '7,24');
pref('extensions.stylishmod.move.restore-down', '4,19');
pref('extensions.stylishmod.move.restore-window', '4,18');
pref('extensions.stylishmod.move.save-button-alt', '1,52');
pref('extensions.stylishmod.move.save-button-disabled', '1,48');
pref('extensions.stylishmod.move.save-button-enabled', '1,44');
pref('extensions.stylishmod.move.scratchpad1', '4,8');
pref('extensions.stylishmod.move.scratchpad2', '4,16');
pref('extensions.stylishmod.move.select', '2,36');
pref('extensions.stylishmod.move.settings', '1,4');
pref('extensions.stylishmod.move.space1', '4,15');
pref('extensions.stylishmod.move.space2', '4,16');
pref('extensions.stylishmod.move.spacer1', '5,18');
pref('extensions.stylishmod.move.spacer2', '5,19');
pref('extensions.stylishmod.move.spacer3', '5,20');
pref('extensions.stylishmod.move.spacer4', '5,21');
pref('extensions.stylishmod.move.spacer5', '5,22');
pref('extensions.stylishmod.move.sq-bracket', '4,5');
pref('extensions.stylishmod.move.styleid', '1,36');
pref('extensions.stylishmod.move.style-name', '1,32');
pref('extensions.stylishmod.move.style-page', '1,28');
pref('extensions.stylishmod.move.togglebars', '1,12');
pref('extensions.stylishmod.move.undo', '2,20');
pref('extensions.stylishmod.move.undo-all', '2,22');
pref('extensions.stylishmod.move.unobfuscate', '4,6');
pref('extensions.stylishmod.move.unpreview', '2,32');
pref('extensions.stylishmod.move.update', '3,24');
pref('extensions.stylishmod.move.wrap-lines', '3,8');


